### ISSUE TITLE
investigate sic codes

### ISSUE THREAD

**Issue by india-kerle** [nestauk/dap_prinz_green_jobs#115]
@lizgzil has spotted a potential bug with a SIC name:

```
have you seen that when 'sic_name'= 'ACTIVITIES OF EXTRATERRITORIAL ORGANISATIONS AND BODIES', then sic_id is "na". Don't suppose it matters too much, but worth noting 
```

have a look at the sic name/code/dictionary to ensure that its being correctly mapped.

**Comment by lizgzil** [comment]
<img width="470" alt="Screenshot 2023-12-14 at 12 58 06" src="https://github.com/nestauk/dap_prinz_green_jobs/assets/15956065/499b2c0e-2160-40df-a8a9-5f22292d1ea0">

It seems like this is only a problem when SIC=Nan? maybe sic_names[nan]='ACTIVITIES OF EXTRATERRITORIAL ORGANISATIONS AND BODIES'.

It might not be much of a problem anymore if we are moving forward with reporting at the full SIC code and not the SIC 2 digit?

**Comment by india-kerle** [comment]
part of me wonders if there is a small bug and this is why we originally had 80% coverage of SIC codes that went down to 65% after making post-processing changes...

**Comment by lizgzil** [comment]
was it 80% on the mixed sample? Maybe green jobs are more likely to have company descriptions?

**Comment by lizgzil** [comment]
this isn't a bug with the SIC mapper, it's a bug with the way the SIC 2 was calculated in `process_ojo_green_measures.py`!

When we do:
```
sic_data = load_sic()
sic_names = dict(
        zip(sic_data["Division"].tolist(), sic_data["Description"].tolist())
    )
```

it creates a {'na': 'ACTIVITIES OF ....'} key (since the dataset has 'na' as a string not a null).

Then when we do 
```
all_green_measures_df["SIC_2_digit"] = all_green_measures_df["SIC"].apply(
        lambda x: str(x)[0:2] if x else None
    )
```
it converts the None's into string "nan" and then "nan"[0:2] maps to "na"!!!

Furthermore (and this is a biggie!), when we do:

```
sic_names = dict(
        zip(sic_data["Division"].tolist(), sic_data["Description"].tolist())
    )
```
we aren't actually getting the division name we are getting the sub class name!

It's all fixed by

```
sic_data = load_sic()
    sic_data = sic_data[sic_data["Level headings"]=='Division']
    sic_names = dict(
        zip(sic_data["Division"].tolist(), sic_data["Description"].tolist())
    )

    # Add these new columns
    all_green_measures_df["SIC_2_digit"] = all_green_measures_df["SIC"].apply(
        lambda x: str(x)[0:2] if pd.notnull(x) else None
    )
    all_green_measures_df["SIC_2_digit_name"] = all_green_measures_df[
        "SIC_2_digit"
    ].apply(lambda x: sic_names.get(x) if pd.notnull(x) else None)
```

What a triple pronged issue!!! Anyway, fixed this, but I guess it makes no difference since we arent using sic2 anymore
