### ISSUE TITLE
What entities can we extract

### ISSUE THREAD

**Issue by india-kerle** [nestauk/dap_prinz_green_jobs#33]
Look through a sample of job adverts and check whats actually there and how often
- company names?
- occupation info?
- industry info?
- qualifications
- additional info - e.g. paragraphs about green washing

Do it in label studio?

**Comment by lizgzil** [comment]
# questions from v1 labelling.
- do we tag every single mention of the job title and company name in the text?
![Screenshot 2023-06-06 at 14 49 09](https://github.com/nestauk/dap_prinz_green_jobs/assets/15956065/f8c8d3e1-7a93-4d0b-868e-1f2224712558)
 - Extra info about the occupation needed? Maybe we should allow "OCC_NAME" to cover all the spans we think are useful in identifying the most appropriate standardised occupation name  e.g.
 `Position - Cover SupervisorType of work - KS3/KS4` - its useful for SOC to have the KS3/4 info. 
- sometimes the company sector might be hidden in other parts 
` an experienced sales professional who has sold into the surgical market place`
 - company sector may mostly be inferred from the company description? So can we just tag any mention of the sector as a company description tag?
 - greenwashing? I'm not sure we can make the call. Might be better to tag parts of the advert that mention anything to do with environmental things - and then later make our mind up as to whether assume all the high GHG emissions companies with environmental paragraphs are green washing
 
 ## Company name thoughts
 - what should we do about recruiter company names ? and even recruiter descriptions? 
  - `Vision-FS Recruitment is a leading Financial Services Recruitment business covering the UK FS market.`
  - `Prospero Teaching is looking for a Cover supervisor for an Ofsted "Good" Secondary school Enfield. The school is a mixed school with a very supportive SLT`
 - multiple company names/parent companies? e.g. ARAMARK is the company, but they also refer to the company as Chessington World of Adventures?
 - sometimes a mix of company and recruiter names `Sales Consultant - Surgical Solutions4578634Highbridge Talent`
 - umbrella companies? the job is in one part of their company e.g. "food", but actually the whole company is "sales"
 
 ## Company description thoughts
  - the description of the company might be eluded to in the job tasks? e.g.
 `All our Team Members enjoy a fast paced and high-pressure environment, ensuring that our holiday homes are presented to the highest quality to create the "home from home" experience our holiday makers have grown to expect` for Haven holidays
  - in terms of doing lots of things with the company descriptions- it might be good to tag entire sentences which mention anything to do with the company rather than small spans of text. e,g,
   -   `We are looking for a passionate and motivated Project Manager that is keen on impacting lives of vulnerable young people and adults at risk of homelessness in Camden` this isn't all about the company, but it does contain useful info about what type of company this is.
   - although there is also this example which might be too much info `A world leader in design and manufacturing of leading edge technologies is looking for a Quality Manager to be based at their site in Eastbourne to join their growing engineering team.`
 - company description has so much values+sales in and may not even say what the company does e.g. in this case they are a residential management agent
![Screenshot 2023-06-06 at 15 02 00](https://github.com/nestauk/dap_prinz_green_jobs/assets/15956065/11096b17-662d-40fd-890d-541f33166d5d)
- company descriptions/industry can sometimes be inferred from the experience needed?
`looking for candidates with a minimum 5 years’ experience within Manufacturing, Construction or Heavy Plant industries`

 ## What are we actually going to do with these labels?
 - in some cases its for NER e.g. qualifications - so labelling every one is important
 - in some cases its a classifier e.g. job text -> occupation - so just labelling one would be fine?
 - using any and all the text to do with the company to predict SIC?

**Comment by india-kerle** [comment]
v1 labelling:
- how to label 'green washing'? #1726 job advert is a major airline that claims to be sustainable? from an NER perspective, nothing in the text says it (except very polluting industry and maaany words of sustainability) - we could look for this kind of relationship but i don't think we could extract phrases  
- we could also extract company benefits 
- #1883 job advert - thoughts on how to deal job advert having a list of 'key words' incl. list of job tittles 
- #2001 - its radioactive waste in the public sector but no span connects the two 
- company_sector > company_desc? i.e. where possible, get the most concise description of the sector?
- climate-y skills feel like having specialist knowledge of something is helpful 
- do we get rid of or include company stopwords like ltd etc. for company names?

What are we actually going to do with these labels?
- occs - feels like we can focus on disambiguation of job_title_raw or extract a cleaner occupation name in the job description but don't think we need both
- industry/company_name - where the company is posting the job advert, there generally are company descriptions but where it is posted by a recruiter, its generally a company sector phrase. Should not extract recruitment company name

**Comment by india-kerle** [comment]
ok i've labelled ~20ish jobs and here are my thoughts:

extracting...
- occupation: this feels extremely do-able and I actually wonder if we just extract occupation from descriptions to get rid of bad entries in the job_title_raw.
- qualifications: this also feels like a simple task i.e. many phrases explicitly have the phrase 'qualification' - the challenge here feels like splitting lists of qualifications 
- company_name: this feels extremely do-able (can use pre-trained models for this!) but we will want to disambiguate for recruiting vs. early disambiguation thoughts: recruitment job ads _generally_ appear to not include much company description; there's that recruitment metadata field; they often explicitly say 'recruiting for...'
- company_sector/company_description: this feels like the most challenging task. We may want to manually try to match to SIC and see how that goes. 

I thought the pydata person who suggested giving a 'job advert quality score' could be onto something given some of these complexities mentioned in my/your post

**Comment by lizgzil** [comment]
- no greenwashing tag
- no company name tag
- no occupation name tag

- keep company description and company sector
- part 1 label company description whole sentences at a time without thinking about the SIC task.
- part 2 use the company sector in the company description to help with SIC

- qualification - label separately or together

nice
- company benefits - only to do if we have prodigy and openai. test it out as a tagging exercise and if its not too much of a pain. any hurdle then scrap. could be a standalone tagging exercise not using LLM.
- could use SIC or company description to help with SOC. secondary school company mentioned in "teacher" job advert

**Comment by india-kerle** [comment]
@lizgzil given we've bought prodigy, it feels like the entities we will extract are:

1. company description
2. company sector
3. qualification
4. skill (for skills improvement)
5. multiskill (for skills improvement)
6. company benefit

alright to close then?

**Comment by lizgzil** [comment]
> @lizgzil given we've bought prodigy, it feels like the entities we will extract are:
> 
> 1. company description
> 2. company sector
> 3. qualification
> 4. skill (for skills improvement)
> 5. multiskill (for skills improvement)
> 6. company benefit
> 
> alright to close then?

sure!

**Comment by lizgzil** [comment]
Putting this here too:

@india-kerle the first pass on 35 labelled job adverts gave us these proportions of job adverts containing the tags:

```
{'QUALIFICATION': 0.5142857142857142,
 'COMP_DESC': 0.6,
 'COMP_SECTOR': 0.6857142857142857,
 'OCC_NAME': 1.0,
 'COMP_NAME': 0.9714285714285714}
 ```
 
 These were the COMP_DESC's found:
 ```
 [['Prospero Teaching is looking for a Cover supervisor for an Ofsted "Good" Secondary school Enfield. The school is a mixed school with a very supportive SLT. The school highly values their staff and the students are always engaged in lifelong learning.',
  'SECONDARY SCHOOL'],
 ["This is an award-winning UK Financial Advisor | Wealth Manager which has rapidly grown into a national business, offering Financial Advice, Wealth Management services to HNW individuals. Its unique proposition is a one stop shop for education, guidance, and advice to the employees of major corporate business in the UK. Growth to date has been driven because the company's services has become the new HR best practice for leading employers"],
 ["help brands end waste.To do this, they've created the world's first-ever circular supply chain which allows them to make new products from waste material"],
 ['the UK’s leading access control providers offering an extensive range of turnstiles, access control systems and bespoke touch screen kiosks, building up a large client base in the leisure industry'],
 ['one of the world’s leading airline groups and owner of some of the biggest brands in the sky. With a diverse workforce spread across four countries, we provide creative and innovative solutions to drive sustainable transformation by delivering finance, procurement, and airline services, as well as group-wide systems across group. Each operating company benefits from our centralised model, driving efficiencies, automation, and economies of scale. Our vision is to increase shareholder value, accelerate business performance, delight customers, enable employees, and protect our business through the innovative and agile use of technology and data'],
 ['PE backed, high growth engineering company that is internationally recognised'],
 ["Our client is one of the UK's prestigious mortgage brokerages that specialises in working closely with HNW individuals advising on their complex and / or high value mortgages. They have close relationships with private banks and specialist lenders to secure individually tailored solutions"],
 ['A world leader in design and manufacturing of leading edge technologies'],
 ['a global manufacturer of residential heating, plumbing, ventilation and renewable technologies with an extensive portfolio of premium high quality products, providing the latest in energy efficiencies and industry regulatory requirements'],
 ['This recession proof business manufacture, hire and maintain HGV Vehicles for various industries'],
 ['"escape from urban living" experience'],
 ['market leader in supplying low carbon technology solutions (technologies that can be used to provide heat for a building, emitting low or no net CO2 emissions) within the UK’s building services sector through their energy efficient range of heating, cooling and ventilation solutions. At SAV, we work with global, market leading technology partners to offer a range of innovative and award winning product solutions aimed at both reducing the carbon footprint and combatting fuel poverty'],
 ['Project Manager',
  'Depaul UK works with some of the most disadvantaged young people in the UK.',
  'impacting lives of vulnerable young people and adults at risk of homelessness',
  'Camden Kalidsescope is a unique project working in close partnership with local mental health services\xa0providing a holistic support package to clients who have\xa0enduring mental health conditions.'],
 ['provider of Ofqual-regulated qualifications, developing and delivering a suite of qualifications in fire safety and risk assessment, and occupational safety and health'],
 ['PR & Comms agency, specialists in Environmental and Sustainability focussed campaigns'],
 ['highly successful, reputable, and leading property and construction consultancy'],
 ["In part as a result of covid and increased awareness of environmental and sustainability issues, there is an increased demand for reusable textiles within the surgical environment, we're looking for someone passionate and enthusiastic to drive sales growth through both clinical and non clinical decision makers"],
 ['market leading manufacturer of containment storage solutions'],
 ['This Client is an engineering consultancy with capabilities in electronics design, PCB layout, embedded software, application software, mechanical design, automation and machine vision'],
 ['We are One Team at Chessington World of Adventures Resort and we are committed to deliver magic every day for our guests! This is an exciting opportunity to be part of something very special at a major UK theme park attracting 1000s of guests during peak season!',
  'Aramark is a leading service and solutions provider in Northern Europe. We proudly support clients, partners and customers in food, facilities management, property services, and retail solutions. We believe a career should develop your talents, fuel your passions, and empower your professional growth. So, no matter what you’re pursuing — a new challenge, a sense of belonging, or just a great place to work — our focus is helping you reach your full potential.'],
 ["Rendall & Rittner is a place where hard work is acknowledged and rewarded, where development is nurtured and supported, where values are never compromised and where success is celebrated. We are a responsible modern organisation, with best practice a fundamental part of our DNA. We're ever conscious of the need for balance: superlative client service with sustainability; management excellence with staff motivation; financial prudence with a permanent programme of growth and improvement. At Rendall & Rittner, we focus on delivering outstanding management to our clients and lessees. We are constantly developing initiatives to ensure that our day-to-day management is as effective as possible. Key services and strategies include our innovative approach to management and customer service, our dedication to corporate social responsibility and investment in our staff."]]
 ```
 so seems doable to use these to extract industries?
 
  These were the COMP_SECTOR's found:
 ```
 [['Secondary school'],
 ['Financial Advisor | Wealth Manager'],
 ['facilities management'],
 ['Education'],
 ['Sustainability brand'],
 ['access control providers'],
 ['airline groups'],
 ['engineering'],
 ['construction'],
 ['mortgage brokerage'],
 ['manufacturer of residential heating, plumbing, ventilation and renewable technologies'],
 ['manufacturing company'],
 ['holiday homes'],
 ['sustainability/ energy efficiency technology'],
 ['building services sector'],
 ['Education'],
 ['storing and managing radioactive waste', 'Public Sector'],
 ['infrastructure services and engineering consultancy'],
 ['health and safety qualifications', 'occupational safety and health'],
 ['transport'],
 [' beauty and wellness'],
 ['PR and Communications',
  'PR / Communications',
  'PR & comms',
  'PR & Comms agency'],
 ['sales professional who has sold into the surgical market place'],
 ['engineering consultancy']]
 ```
 
For the 15 job adverts with both a company sector span and a description span:
- 9/15 have an instance of a sector span contained in a description span
- 6/15 don't have any sector span contained in a description span
